# .pre-commit-config.yaml
repos:
-  repo: https://github.com/awslabs/cfn-python-lint
   rev: v0.15.0 #The vesrion of cfn-lint to use
   hooks:
   -   id: cfn-python-lint
       files: template/.*\.(json|yml|yaml)$
